### ISSUE TITLE
configure on standard Debian 11 (alpha 3)

### ISSUE THREAD

**Issue by kalpha2** [mdbtools/gmdb2#3]
configure on standard Debian 11 (alpha 3). I have 
`sudo apt-get install mdbtools mdbtools-dev odbc-mdbtools unixodbc unixodbc-dev`
`git clone https://github.com/mdbtools/gmdb2.git`

I then try
`autoreconf -f -i -Wno-portability`
`./configure`

which results in
`checking for libmdb >= 0.9.0... yes
checking for libmdbsql >= 0.9.0... yes
checking for gtk+-2.0 >= 2.14 libglade-2.0 libgnomeui-2.0... no
configure: error: Could not find GNOME libraries, which are required to build gmdb2.
`
Re requirements from github page

`This is the official GUI for mdbtools. It requires:`
`    GTK+ 2.14 or later
    libglade-2.0
    libgnomeui-2.0
`
I found libglade2 and have installed
`sudo apt-get install libglade2-dev`

But I still get same error and
(a) I cannot find libgnomeui-2.0 in bullseye 
and
(b) I'm not sure what package(s) I need for GTK+2.14 ?

**Comment by evanmiller** [comment]
I believe that libgnomeui-2.0 is no longer included in Debian. (This is why gmdb2 is no longer a Debian package; the old Stretch package is here: https://packages.debian.org/stretch/gnome/mdbtools-gmdb)

For GTK I think this is the package you want:

https://packages.debian.org/stretch/libgtk2.0-dev

You can see the full list of required packages in the GitHub Actions configuration:

https://github.com/mdbtools/gmdb2/blob/main/.github/workflows/build.yml

**Comment by kalpha2** [comment]
so libgtk2.0-dev is already installed ... v2.24.33-1 
re `I believe that libgnomeui-2.0 is no longer included in Debian`
does this mean I can not build gmdb2 from source on Debian 11 (Bullseye) ever?
Is it going to need a future gtk3 based gmdb2 (or gmdb3) flavour to be available?

**Comment by evanmiller** [comment]
You might able to install libgnomeui-2.0 manually; I'm not sure. Here is more information about its removal from Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=885767

Someone will need to port the tool to GTK3 for it to be supported into the future. Right now the tool is essentially deprecated, but I'm leaving it up in case anyone finds it useful or wants to update it.

**Comment by evanmiller** [comment]
Please try the latest commits; you should only need `gettext`, `yelp-tools`, and `libgtk-3-dev` to build it.

**Comment by rhurlin** [comment]
JFTR:
I tried you latest patches (https://github.com/mdbtools/gmdb2/commit/861780ae311ac5c8adaff3752c64c7c49483abc5) on **FreeBSD** with gtk3-3.24.29 and it seems to build, install and work quite nice :)

Many thanks for all your work on GMDB2 so far. I am really looking forward to create a FreeBSD port, once gmdb2 0.9.0 is released.

**Comment by evanmiller** [comment]
@rhurlin Would you mind testing out the Help menu? It should open up the Help file in Yelp, which I don't have installed on my dev machine due to some dependency issues.

Updating gmdb2 has been a fun little project... Ended up getting an old version of `glade` running on a hobby computer (2001 iMac retrofitted with an SSD) through MacPorts, and did all the work on there. So the MacPorts folks have some patches in the process. I'll plan to package it up for them too when 0.9 is released.

In the meantime if you hit any serious usability bugs go ahead and open an issue. There are some quirks in the interface, but my goal is to have a final release that is stable, usable, and basically the same program as before.

**Comment by rhurlin** [comment]
I am able to open the Help in a yelp window. All pages seem reachable and complete, the links are functional, graphics are included :)

I can only begin to imagine how much time you have already invested in updating GMDB2. Thanks again for that!

**Comment by evanmiller** [comment]
@rhurlin Excellent to hear. I did excise a couple of in-program Help shortcuts, but I think people will survive for now.

Migrating the interface files was the trickiest part, but Glade 3.10 made it relatively straightforward with re-saves and a few widget replacements. There's a good chance that a widget or combo box here or there doesn't quite work right. In any event I'm hoping the GTK3 migration will put GMDB2 on a good footing for the next decade or so :-).

Since this project is not exactly teeming with beta testers, I'll go ahead and kick out a 0.9.0 release, and then we can put any fixes into 0.9.1. I dropped a line over to Debian (@ nirgal) about reviving their package but I haven't heard back yet. It looks like several distros used to carry it.

The `main` branch is building on Ubuntu, so I'm going to close the open issues before we get too far off topic. We can continue the conversation in a new one.
